# 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.Tensor`

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [16]:
TENSOR[0][1]

tensor([3, 4, 5])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to betters represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
# Create a random tensors of size (2,3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.1470, 0.5257, 0.4817, 0.1549],
         [0.7784, 0.9697, 0.8132, 0.0146],
         [0.2016, 0.4774, 0.6111, 0.8302]],

        [[0.5213, 0.9204, 0.7692, 0.4610],
         [0.4828, 0.1632, 0.6676, 0.1509],
         [0.9840, 0.2806, 0.1822, 0.0048]]])

In [18]:
random_tensor.ndim

3

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.arange
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
some_tensor = torch.arange(start=0, end=1000, step=80)
some_tensor

tensor([  0,  80, 160, 240, 320, 400, 480, 560, 640, 720, 800, 880, 960])

In [26]:
# Creating tensors like
some_zeros = torch.zeros_like(input = some_tensor)
some_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors we'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 12.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is yout tensor on (by default, it ,is on cpu)
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([ 3.,  6., 12.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([ 3.,  6., 12.], dtype=torch.float16)

In [30]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4721, 0.3835, 0.3969, 0.1114],
        [0.1668, 0.4363, 0.6827, 0.5741],
        [0.7487, 0.0026, 0.7358, 0.4156]])

In [32]:
# Find out details about some_tensor
print(some_tensor)
print(f"Dataytype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4721, 0.3835, 0.3969, 0.1114],
        [0.1668, 0.4363, 0.6827, 0.5741],
        [0.7487, 0.0026, 0.7358, 0.4156]])
Dataytype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [33]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Try out PyTorch in-built functions
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multipllication

Two main ways of performing multiplication in neural networks and deep learning:

1- Element-wise multiplication

2- Matrix multiplication (dot product)

In [36]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [37]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [38]:
### One of the most common errors in Deep Learning: Shape errors
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.mm() is the same as torch.matmul()

In [39]:
# Matrix multiplication with tensor_A and transpose of tensor_B
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [40]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [42]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [43]:
# torchçmean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [44]:
# Find the sum
torch.sum(x)

tensor(450)

## Finding the positional min and max

In [45]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [47]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsequeezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memort as the original tensor
* Stacking - combine multpile tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permutted (swapped) in a certain way

In [48]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [50]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
# Changing z changes x (because a view of a tensor shares the same memeory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [52]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [53]:
x_reshaped = x_reshaped.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"x_squeezed: {x_squeezed}")
print(f"x squeezed shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f": x_unsqueezed: {x_unsqueezed}")
print(f"x_unsqueezed shape: {x_unsqueezed.shape}")

x_squeezed: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
x squeezed shape: torch.Size([9])
: x_unsqueezed: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
x_unsqueezed shape: torch.Size([1, 9])


In [56]:
x_unsqueezed2 = x_squeezed.unsqueeze(dim=1)
x_unsqueezed2

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [57]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # Shifts axis 0 to 1, 1 to 2, 2 to 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [58]:
x_original[0,0,0] = 123456
x_original[0,0,0], x_permuted[0,0,0]

(tensor(123456.), tensor(123456.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [59]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [60]:
# Indexing on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
# Indexing on the middle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [62]:
# Indexing on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

## PyTorch tensors  NumPy

- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [63]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # .type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [64]:
 # Chenging the value of the array
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [65]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_array = tensor.numpy()
tensor, numpy_array 

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [66]:
tensor += 1
tensor, numpy_array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducability (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

In [67]:
import torch

# Create 2 random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

# Set the random seed 
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"\n {random_tensor_C}")
print(f"\n {random_tensor_D}")

print("\n Checking if random_tensor_C is equal to random_tensor_D")
print(random_tensor_C == random_tensor_D)

tensor([[0.0905, 0.9629, 0.7235, 0.6696],
        [0.2448, 0.0681, 0.0449, 0.8439],
        [0.6708, 0.4249, 0.8517, 0.7152]])
tensor([[0.0374, 0.5745, 0.7843, 0.3927],
        [0.3616, 0.0243, 0.9452, 0.1569],
        [0.2028, 0.9878, 0.0190, 0.2845]])

 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 Checking if random_tensor_C is equal to random_tensor_D
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

1. Easiest - Use Google Colab 
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure; these servies allow you to rent computers on the cloud and access them

In [68]:
!nvidia-smi

Fri Sep 30 14:06:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [71]:
# Check for GPU
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

In [72]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [73]:
# Count number of devices
torch.cuda.device_count()

1

##3. Putting tensors and models on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [74]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device="cpu") # byu default it is also cpu
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [75]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [77]:
# If tensor is on the GPU, can't transform it to NumPy
# tensor_on_gpu.numpy() -> this will throw an error

In [78]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])