## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.Tensor`

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [16]:
TENSOR[0][1]

tensor([3, 4, 5])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to betters represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
# Create a random tensors of size (2,3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.2514, 0.7269, 0.6280, 0.4074],
         [0.2889, 0.5186, 0.5347, 0.9768],
         [0.3389, 0.8344, 0.4246, 0.3091]],

        [[0.2110, 0.4038, 0.8467, 0.3261],
         [0.0190, 0.8190, 0.4939, 0.3851],
         [0.7194, 0.3122, 0.6551, 0.2564]]])

In [18]:
random_tensor.ndim

3

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.arange
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
some_tensor = torch.arange(start=0, end=1000, step=80)
some_tensor

tensor([  0,  80, 160, 240, 320, 400, 480, 560, 640, 720, 800, 880, 960])

In [26]:
# Creating tensors like
some_zeros = torch.zeros_like(input = some_tensor)
some_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors we'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 12.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is yout tensor on (by default, it ,is on cpu)
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([ 3.,  6., 12.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([ 3.,  6., 12.], dtype=torch.float16)

In [30]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3351, 0.7034, 0.8019, 0.6389],
        [0.6228, 0.9945, 0.0505, 0.7399],
        [0.0665, 0.1021, 0.1645, 0.5502]])

In [32]:
# Find out details about some_tensor
print(some_tensor)
print(f"Dataytype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3351, 0.7034, 0.8019, 0.6389],
        [0.6228, 0.9945, 0.0505, 0.7399],
        [0.0665, 0.1021, 0.1645, 0.5502]])
Dataytype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [2]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [3]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [5]:
# Try out PyTorch in-built functions
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multipllication

Two main ways of performing multiplication in neural networks and deep learning:

1- Element-wise multiplication

2- Matrix multiplication (dot product)

In [6]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [7]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [22]:
### One of the most common errors in Deep Learning: Shape errors
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.mm() is the same as torch.matmul()

In [23]:
# Matrix multiplication with tensor_A and transpose of tensor_B
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [25]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [27]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [30]:
# torchçmean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [31]:
# Find the sum
torch.sum(x)

tensor(450)

## Finding the positional min and max

In [32]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [35]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsequeezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memort as the original tensor
* Stacking - combine multpile tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permutted (swapped) in a certain way

In [51]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [53]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# Changing z changes x (because a view of a tensor shares the same memeory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [57]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [66]:
x_reshaped = x_reshaped.reshape(1,9)
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])