## 00. PyTorch Fundamentals

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.Tensor`

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [25]:
TENSOR[0][1]

tensor([3, 4, 5])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to betters represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [28]:
# Create a random tensors of size (2,3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.4099, 0.5933, 0.5426, 0.8703],
         [0.6394, 0.8336, 0.1216, 0.3240],
         [0.1906, 0.8753, 0.2379, 0.4762]],

        [[0.2999, 0.6372, 0.5822, 0.7637],
         [0.3466, 0.8090, 0.9074, 0.1819],
         [0.6599, 0.6924, 0.2996, 0.7277]]])

In [29]:
random_tensor.ndim

3

In [34]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [36]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

In [39]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [41]:
# Use torch.arange
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
some_tensor = torch.arange(start=0, end=1000, step=80)
some_tensor

tensor([  0,  80, 160, 240, 320, 400, 480, 560, 640, 720, 800, 880, 960])

In [44]:
# Creating tensors like
some_zeros = torch.zeros_like(input = some_tensor)
some_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors we'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [49]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 12.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is yout tensor on (by default, it ,is on cpu)
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([ 3.,  6., 12.])

In [50]:
float_32_tensor.dtype

torch.float32

In [51]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([ 3.,  6., 12.], dtype=torch.float16)

In [53]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [55]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6796, 0.7626, 0.3478, 0.9714],
        [0.3321, 0.6400, 0.8084, 0.1609],
        [0.0620, 0.4410, 0.9985, 0.6973]])

In [57]:
# Find out details about some_tensor
print(some_tensor)
print(f"Dataytype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6796, 0.7626, 0.3478, 0.9714],
        [0.3321, 0.6400, 0.8084, 0.1609],
        [0.0620, 0.4410, 0.9985, 0.6973]])
Dataytype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
